services:
  db:
    image: postgres:16.1
    container_name: postgres_new
    ports:
      - "6432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=later
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "bash", "-c", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 5s
      retries: 10